extends:
  - alloy
  - alloy/react
  - alloy/typescript
rules:
  # https://eslint.org/docs/rules/no-trailing-spaces
  no-trailing-spaces: error
  # https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-curly-brace-presence.md
  react/jsx-curly-brace-presence: off
  # https://reactjs.org/docs/hooks-rules.html
  react-hooks/exhaustive-deps: off
overrides:
  - files: ['**/*.js']
    rules:
      '@typescript-eslint/no-require-imports': off
  - files: ['**/*.ts', '**/*.tsx']
    rules:
      no-unreachable: off
      no-unused-vars: off
      '@typescript-eslint/no-unused-vars': off
      no-unused-expressions: off
      '@typescript-eslint/no-unused-expressions':
        - error
        - allowShortCircuit: true
          allowTernary: true
          allowTaggedTemplates: true
