language: node_js

node_js:
  - 12

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libx11-dev
      - libxtst-dev
      - libasound2-dev
      - libavformat-dev
      - libass-dev
      - g++-4.8
      - gcc-4.8

cache:
  npm: true

git:
  depth: false

before_install:
  - g++ --version
  - $CXX --version

script:
  - npm run build

deploy:
  - provider: npm
    skip_cleanup: true
    email: "${NPM_USER_EMAIL}"
    api_key: "${NPM_AUTH_TOKEN}"
    on:
      branch: master
      tags: true

notifications:
  email: true
  on_success: always
  on_failure: always
