import { NoteCode as Note } from './midi'
import { NamedKey as Key } from './keyboard'

export type PortalMap = Record<Note, Key>
export type FnPortalMaps = Partial<Record<Note, Partial<PortalMap>>>

export const TemplatePortal: PortalMap = {
  [Note.C2]: Key.NULL,
  [Note.CSharp2]: Key.NULL,
  [Note.D2]: Key.NULL,
  [Note.DSharp2]: Key.NULL,
  [Note.E2]: Key.NULL,
  [Note.F2]: Key.NULL,
  [Note.FSharp2]: Key.NULL,
  [Note.G2]: Key.NULL,
  [Note.GSharp2]: Key.NULL,
  [Note.A2]: Key.NULL,
  [Note.ASharp2]: Key.NULL,
  [Note.B2]: Key.NULL,

  [Note.C1]: Key.NULL,
  [Note.CSharp1]: Key.NULL,
  [Note.D1]: Key.NULL,
  [Note.DSharp1]: Key.NULL,
  [Note.E1]: Key.NULL,
  [Note.F1]: Key.NULL,
  [Note.FSharp1]: Key.NULL,
  [Note.G1]: Key.NULL,
  [Note.GSharp1]: Key.NULL,
  [Note.A1]: Key.NULL,
  [Note.ASharp1]: Key.NULL,
  [Note.B1]: Key.NULL,

  [Note.C]: Key.NULL,
  [Note.CSharp]: Key.NULL,
  [Note.D]: Key.NULL,
  [Note.DSharp]: Key.NULL,
  [Note.E]: Key.NULL,
  [Note.F]: Key.NULL,
  [Note.FSharp]: Key.NULL,
  [Note.G]: Key.NULL,
  [Note.GSharp]: Key.NULL,
  [Note.A]: Key.NULL,
  [Note.ASharp]: Key.NULL,
  [Note.B]: Key.NULL,

  [Note.c]: Key.NULL,
  [Note.cSharp]: Key.NULL,
  [Note.d]: Key.NULL,
  [Note.dSharp]: Key.NULL,
  [Note.e]: Key.NULL,
  [Note.f]: Key.NULL,
  [Note.fSharp]: Key.NULL,
  [Note.g]: Key.NULL,
  [Note.gSharp]: Key.NULL,
  [Note.a]: Key.NULL,
  [Note.aSharp]: Key.NULL,
  [Note.b]: Key.NULL,

  [Note.c1]: Key.NULL,
  [Note.cSharp1]: Key.NULL,
  [Note.d1]: Key.NULL,
  [Note.dSharp1]: Key.NULL,
  [Note.e1]: Key.NULL,
  [Note.f1]: Key.NULL,
  [Note.fSharp1]: Key.NULL,
  [Note.g1]: Key.NULL,
  [Note.gSharp1]: Key.NULL,
  [Note.a1]: Key.NULL,
  [Note.aSharp1]: Key.NULL,
  [Note.b1]: Key.NULL,

  [Note.c2]: Key.NULL,
  [Note.cSharp2]: Key.NULL,
  [Note.d2]: Key.NULL,
  [Note.dSharp2]: Key.NULL,
  [Note.e2]: Key.NULL,
  [Note.f2]: Key.NULL,
  [Note.fSharp2]: Key.NULL,
  [Note.g2]: Key.NULL,
  [Note.gSharp2]: Key.NULL,
  [Note.a2]: Key.NULL,
  [Note.aSharp2]: Key.NULL,
  [Note.b2]: Key.NULL,

  [Note.c3]: Key.NULL,
  [Note.cSharp3]: Key.NULL,
  [Note.d3]: Key.NULL,
  [Note.dSharp3]: Key.NULL,
  [Note.e3]: Key.NULL,
  [Note.f3]: Key.NULL,
  [Note.fSharp3]: Key.NULL,
  [Note.g3]: Key.NULL,
  [Note.gSharp3]: Key.NULL,
  [Note.a3]: Key.NULL,
  [Note.aSharp3]: Key.NULL,
  [Note.b3]: Key.NULL,

  [Note.c4]: Key.NULL,
  [Note.cSharp4]: Key.NULL,
  [Note.d4]: Key.NULL,
  [Note.dSharp4]: Key.NULL,
  [Note.e4]: Key.NULL,
  [Note.f4]: Key.NULL,
  [Note.fSharp4]: Key.NULL,
  [Note.g4]: Key.NULL,
  [Note.gSharp4]: Key.NULL,
  [Note.a4]: Key.NULL,
  [Note.aSharp4]: Key.NULL,
  [Note.b4]: Key.NULL,

  [Note.c5]: Key.NULL,
  [Note.cSharp5]: Key.NULL,
  [Note.d5]: Key.NULL,
  [Note.dSharp5]: Key.NULL,
  [Note.e5]: Key.NULL,
  [Note.f5]: Key.NULL,
  [Note.fSharp5]: Key.NULL,
  [Note.g5]: Key.NULL,
  [Note.gSharp5]: Key.NULL,
  [Note.a5]: Key.NULL,
  [Note.aSharp5]: Key.NULL,
  [Note.b5]: Key.NULL,

  [Note.c6]: Key.NULL,
}
