import { NoteCode as Note } from './midi'
import { NamedKey as Key } from './keyboard'

export type PortalMap = Record<Note, Key>
export type FnPortalMaps = Partial<Record<Note, Partial<PortalMap>>>

export const DefaultPortal: PortalMap = {
  [Note.C2]: Key.NULL,
  [Note.C2Sharp]: Key.NULL,
  [Note.D2]: Key.NULL,
  [Note.D2Sharp]: Key.NULL,
  [Note.E2]: Key.NULL,
  [Note.F2]: Key.NULL,
  [Note.F2Sharp]: Key.NULL,
  [Note.G2]: Key.NULL,
  [Note.G2Sharp]: Key.NULL,
  [Note.A2]: Key.NULL,
  [Note.A2Sharp]: Key.NULL,
  [Note.B2]: Key.NULL,

  [Note.C1]: Key.NULL,
  [Note.C1Sharp]: Key.NULL,
  [Note.D1]: Key.NULL,
  [Note.D1Sharp]: Key.NULL,
  [Note.E1]: Key.NULL,
  [Note.F1]: Key.NULL,
  [Note.F1Sharp]: Key.NULL,
  [Note.G1]: Key.NULL,
  [Note.G1Sharp]: Key.NULL,
  [Note.A1]: Key.NULL,
  [Note.A1Sharp]: Key.NULL,
  [Note.B1]: Key.NULL,

  [Note.C]: Key.NULL,
  [Note.CSharp]: Key.NULL,
  [Note.D]: Key.NULL,
  [Note.DSharp]: Key.NULL,
  [Note.E]: Key.NULL,
  [Note.F]: Key.NULL,
  [Note.FSharp]: Key.NULL,
  [Note.G]: Key.NULL,
  [Note.GSharp]: Key.NULL,
  [Note.A]: Key.NULL,
  [Note.ASharp]: Key.NULL,
  [Note.B]: Key.NULL,

  [Note.c]: Key.NULL,
  [Note.cSharp]: Key.NULL,
  [Note.d]: Key.NULL,
  [Note.dSharp]: Key.NULL,
  [Note.e]: Key.NULL,
  [Note.f]: Key.NULL,
  [Note.fSharp]: Key.NULL,
  [Note.g]: Key.NULL,
  [Note.gSharp]: Key.NULL,
  [Note.a]: Key.NULL,
  [Note.aSharp]: Key.NULL,
  [Note.b]: Key.NULL,

  [Note.c1]: Key.NULL,
  [Note.c1Sharp]: Key.NULL,
  [Note.d1]: Key.NULL,
  [Note.d1Sharp]: Key.NULL,
  [Note.e1]: Key.NULL,
  [Note.f1]: Key.NULL,
  [Note.f1Sharp]: Key.NULL,
  [Note.g1]: Key.NULL,
  [Note.g1Sharp]: Key.NULL,
  [Note.a1]: Key.NULL,
  [Note.a1Sharp]: Key.NULL,
  [Note.b1]: Key.NULL,

  [Note.c2]: Key.NULL,
  [Note.c2Sharp]: Key.NULL,
  [Note.d2]: Key.NULL,
  [Note.d2Sharp]: Key.NULL,
  [Note.e2]: Key.NULL,
  [Note.f2]: Key.NULL,
  [Note.f2Sharp]: Key.NULL,
  [Note.g2]: Key.NULL,
  [Note.g2Sharp]: Key.NULL,
  [Note.a2]: Key.NULL,
  [Note.a2Sharp]: Key.NULL,
  [Note.b2]: Key.NULL,

  [Note.c3]: Key.NULL,
  [Note.c3Sharp]: Key.NULL,
  [Note.d3]: Key.NULL,
  [Note.d3Sharp]: Key.NULL,
  [Note.e3]: Key.NULL,
  [Note.f3]: Key.NULL,
  [Note.f3Sharp]: Key.NULL,
  [Note.g3]: Key.NULL,
  [Note.g3Sharp]: Key.NULL,
  [Note.a3]: Key.NULL,
  [Note.a3Sharp]: Key.NULL,
  [Note.b3]: Key.NULL,

  [Note.c4]: Key.NULL,
  [Note.c4Sharp]: Key.NULL,
  [Note.d4]: Key.NULL,
  [Note.d4Sharp]: Key.NULL,
  [Note.e4]: Key.NULL,
  [Note.f4]: Key.NULL,
  [Note.f4Sharp]: Key.NULL,
  [Note.g4]: Key.NULL,
  [Note.g4Sharp]: Key.NULL,
  [Note.a4]: Key.NULL,
  [Note.a4Sharp]: Key.NULL,
  [Note.b4]: Key.NULL,

  [Note.c5]: Key.NULL,
  [Note.c5Sharp]: Key.NULL,
  [Note.d5]: Key.NULL,
  [Note.d5Sharp]: Key.NULL,
  [Note.e5]: Key.NULL,
  [Note.f5]: Key.NULL,
  [Note.f5Sharp]: Key.NULL,
  [Note.g5]: Key.NULL,
  [Note.g5Sharp]: Key.NULL,
  [Note.a5]: Key.NULL,
  [Note.a5Sharp]: Key.NULL,
  [Note.b5]: Key.NULL,

  [Note.c6]: Key.NULL,
}
