import { NoteCode as Note } from './midi'
import { NamedKey as Key } from './keyboard'
import { PortalMap, FnPortalMaps, DefaultPortal } from './keyMapping'

export const portal: PortalMap = {
  ...DefaultPortal,

  [Note.C]: Key.NULL,
  [Note.CSharp]: Key.escape,
  [Note.D]: Key.NULL,
  [Note.DSharp]: Key.NULL,
  [Note.E]: Key.NULL,
  [Note.F]: Key.NULL,
  [Note.FSharp]: Key.tab,
  [Note.G]: Key.control,
  [Note.GSharp]: Key.capsLock,
  [Note.A]: Key.alt,
  [Note.ASharp]: Key.shift,
  [Note.B]: Key.command,

  [Note.c]: Key.a,
  [Note.cSharp]: Key.q,
  [Note.d]: Key.z,
  [Note.dSharp]: Key.w,
  [Note.e]: Key.s,
  [Note.f]: Key.x,
  [Note.fSharp]: Key.e,
  [Note.g]: Key.c,
  [Note.gSharp]: Key.d,
  [Note.a]: Key.f,
  [Note.aSharp]: Key.r,
  [Note.b]: Key.v,

  [Note.c1]: Key.space,
  [Note.c1Sharp]: Key.t,
  [Note.d1]: Key.b,
  [Note.d1Sharp]: Key.g,
  [Note.e1]: Key.h,
  [Note.f1]: Key.n,
  [Note.f1Sharp]: Key.y,
  [Note.g1]: Key.j,
  [Note.g1Sharp]: Key.u,
  [Note.a1]: Key.m,
  [Note.a1Sharp]: Key.i,
  [Note.b1]: Key.k,

  [Note.c2]: Key.l,
  [Note.c2Sharp]: Key.o,
  [Note.d2]: Key.comma,
  [Note.d2Sharp]: Key.p,
  [Note.e2]: Key.dot,
  [Note.f2]: Key.slash,
  [Note.f2Sharp]: Key.openBracket,
  [Note.g2]: Key.semicolon,
  [Note.g2Sharp]: Key.closeBracket,
  [Note.a2]: Key.quotes,
  [Note.a2Sharp]: Key.enter,
  [Note.b2]: Key.backslash,

  [Note.c3]: Key.left,
  [Note.c3Sharp]: Key.up,
  [Note.d3]: Key.down,
  [Note.d3Sharp]: Key.up,
  [Note.e3]: Key.right,
  [Note.f3]: Key.delete,
  [Note.f3Sharp]: Key.backspace,
  [Note.g3]: Key.audioVolDown,
  [Note.g3Sharp]: Key.audioVolUp,
  [Note.a3]: Key.lightsMonDown,
  [Note.a3Sharp]: Key.lightsMonUp,
  [Note.b3]: Key.dash,

  [Note.c4]: Key.equal,
}

export const fnPortal: FnPortalMaps = {
  [Note.C]: {
    [Note.cSharp]: Key.f1,
    [Note.d]: Key.f2,
    [Note.dSharp]: Key.f3,
    [Note.e]: Key.f4,
    [Note.f]: Key.f5,
    [Note.fSharp]: Key.f6,
    [Note.g]: Key.f7,
    [Note.gSharp]: Key.f8,
    [Note.a]: Key.f9,
    [Note.aSharp]: Key.f10,
    [Note.b]: Key.f11,

    [Note.c1]: Key.f12,

    [Note.c3]: Key.tilde,
    [Note.c3Sharp]: Key.num1,
    [Note.d3]: Key.num2,
    [Note.d3Sharp]: Key.num3,
    [Note.e3]: Key.num4,
    [Note.f3]: Key.num5,
    [Note.f3Sharp]: Key.num6,
    [Note.g3]: Key.num7,
    [Note.g3Sharp]: Key.num8,
    [Note.a3]: Key.num9,
    [Note.a3Sharp]: Key.num0,
    [Note.b3]: Key.pageUp,

    [Note.c4]: Key.pageDown,
  },

  [Note.CSharp]: {
    [Note.a2Sharp]: Key.NULL,
  },
}
